steps:
  # Docker Image Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/application/flask-contact-app:latest',
      '.'
    ]

  # Docker Image Push
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/application/flask-contact-app:latest'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'flask-contact-service',
      '--image', 'asia-south1-docker.pkg.dev/$PROJECT_ID/application/flask-contact-app:latest',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/application/flask-contact-app:latest'

serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/934139081348-compute@developer.gserviceaccount.com'

options:
  defaultLogsBucketBehavior: LOGGING_ONLY
